# Site wide configuration
title: Suikki devblog
locale: en_US
description: My devblog
#url: http://localhost:4000
url: https://suikki.github.io

# Jekyll configuration
permalink: /:categories/:year/:title
gems:
  - jekyll-feed
  - jekyll-sitemap

# Site owner
owner:
  name: Olli Kallioinen
  nick: suikki
  avatar: /images/blippo.jpg
  email: olli.kallioinen@iki.fi
  twitter: OKallioinen
  github: suikki

disqus-shortname: suikki
google-analytics: UA-78776846-1
